### ISSUE TITLE
BP gets S-mode external interrupt in Machine mode

### ISSUE THREAD

**Issue by Yuan-Mao** [black-parrot/black-parrot#1026]
## Branch / Commit Hash
Current top_dev: [af8beff](https://github.com/black-parrot/black-parrot/commit/af8beffae2470b2564b31eecfcbdf94368bc2196)
## Area
Module 'bp_be_csr'
## Current behavior
In machine mode, riscv hart should not get an S-mode interrupt as per RISCV specification, but BP will get one when I run the following test:

https://gist.github.com/Yuan-Mao/d1a7a96d917a78935e27a4e5218243ae

To get the riscv image, just compile the above test in bp-tests.

**Comment by dpetrisko** [comment]
Hi, that is actually an M-mode interrupt. Although the SIE bit it set, it is set in MIE mode. To make it an S-mode interrupt (and therefore not taken in M-mode), miedeleg.sie should be set
