### ISSUE TITLE
Missing Surelog dependence on Python orderedmultidict

### ISSUE THREAD

**Issue by muwyse** [black-parrot/black-parrot#1037]
## Branch / Commit Hash
All

## Area
tools/Surelog

## Current behavior
running `make surelog` from the repo base directory may result in a build failure for Surelog if the Python `orderedmultidict` module is not found.

## Proposed solution
Add `orderedmultidict` to a dependency list for either BP, or for building Surelog specifically.

Running `pip install orderedmultidict` should resolve the situation.

**Comment by dpetrisko** [comment]
I think this technically should go with the dependencies in here: https://github.com/black-parrot/black-parrot-sim

**Comment by omasanori** [comment]
https://github.com/black-parrot/black-parrot-sim/issues/3

**Comment by dpetrisko** [comment]
Added to doc
