### ISSUE TITLE
Re-enable quad-core accelerator testing in CI

### ISSUE THREAD

**Issue by muwyse** [black-parrot/black-parrot#1054]
## Branch / Commit Hash
#1049 

## Area
CI / accelerators

## Current behavior
#1049 fixes the accelerator configs to instantiate accelerators properly. The config variations are loopback with only streaming loopback accelerators, and vdp with both coherent and streaming accelerators. This causes the existing accelerator test programs to fail for the quad-core configs.

## Expected behavior
quad-core accelerator config tests should report PASS

## Proposed solution
Fix is expected to be a software fix. https://github.com/black-parrot-sdk/bp-tests/issues/30

**Comment by dpetrisko** [comment]
Resolved
