### ISSUE TITLE
Refactor/rewrite Accelerators; convert to BedRock Burst interface

### ISSUE THREAD

**Issue by muwyse** [black-parrot/black-parrot#1055]
## Branch / Commit Hash
#1049 

## Area
top/accelerators

## Current behavior
The current accelerator designs should use BedRock Burst interfaces to reduce complexity and remove conversions between protocols. #1049 makes some changes to the accelerator tiles to align their interfaces with the rest of the BP tiles.

The accelerator designs do not support > 1 burst length transactions, and the separation of combinational and sequential logic needs refactoring.

## Expected behavior
Aside from the interface change, behavior of the accelerators will not change.

## Analysis
Change should remove protocol conversions, improving performance and reducing complexity. Code cleanup will make modules much more maintainable.

## Verification
standard CI, see #1054, too

**Comment by dpetrisko** [comment]
Closing; Accelerators have been changed to use stream pumps
