### ISSUE TITLE
Can't find black-parrot-sdk/prog directory

### ISSUE THREAD

**Issue by garyz712** [black-parrot/black-parrot#1223]
## Branch / Commit Hash
What version of BlackParrot are you running?
master
## Area
Module/tool/makefile/script in question.

## Background information gathered
A clear and concise description of what you already know.
I am running the test command here:
https://github.com/black-parrot/black-parrot/blob/master/docs/eval_guide.md

## Question
A clear and concise description of what is unclear.
When I run the example testing command with verilator, I got this error:

 syn % make [build_dump.sc](http://build_dump.sc/) [sim_dump.sc](http://sim_dump.sc/) SUITE=bp-tests PROG=hello_world
make: Nothing to be done for `[build_dump.sc](http://build_dump.sc/)'.
make: *** No rule to make target `/Users/junyangzhang/Desktop/GenAI4HW/src/data/hardware/01_dataset/black-parrot/../black-parrot-sdk/prog/bp-tests/hello_world.riscv', needed by `/Users/junyangzhang/Desktop/GenAI4HW/src/data/hardware/01_dataset/black-parrot/bp_top/syn/results/verilator/bp_tethered.e_bp_default_cfg.none.sim.bp-tests.hello_world/prog.riscv'. Stop.

However, there is no prog directory inside black-parrot-sdk folder. Am I downloading the right sdk folder? If not, where to get the right one?

## Additional context
Add any other context about the question here.
Logs, screenshots or videos that relate to the question are very helpful.

**Comment by dpetrisko** [comment]
Follow the instructions here:
https://github.com/black-parrot-sdk/black-parrot-sdk?tab=readme-ov-file#building-the-sdk

The SDK has the tools, but you have to compile the programs yourself following these steps
