### ISSUE TITLE
Unsupported features for OpenSBI boot

### ISSUE THREAD

**Issue by dpetrisko** [black-parrot/black-parrot#147]
OpenSBI supports a very limited amount of emulation. We can either hack it to bits or wait until we have this support.

1) Multiply
2) (Hard) Floating point support
3) Atomics (although I believe we can insert our emulation library here)

**Comment by taylor-bsg** [comment]
What determines what OpenSBI does or not support? Is that OSBI the standard
or the implementation?

**Comment by dpetrisko** [comment]
OpenSBI is the open-source implementation (https://github.com/riscv/opensbi) of the RISC-V SBI Spec (https://github.com/riscv/riscv-sbi-doc/blob/master/riscv-sbi.md)

**Comment by taylor-bsg** [comment]
In what way does it support or not support
emulation? Does it mostly run in m-mode and the make use of those features
in m-mode?

**Comment by dpetrisko** [comment]
Does not support may be overstating it.  It runs in M-mode and emulates operations from lower privilege modes.  For these operations, it uses multiply, float and atomics and doesn't provide a mechanism to emulate them yourself.  For floats specifically, it flags a build error if you try to link with softfloat libraries.

I have no doubt given enough hacking that we can get past it, but if we're implementing these features anyway, it's not necessarily worth the effort.  BBL can compile with just RV64I and is also capable of booting Linux

**Comment by taylor-bsg** [comment]
The SBI is basically the BIOS right? So we don’t need to be software
compatible?

What does it use floats for?

M

**Comment by dpetrisko** [comment]
Tagging in @HelloKayT for the first two questions.

Looking into it, it seems to only deal with managing the float regfile and fcsr, so it's probably possible to just rip out those calls. Doesn't actually use fpu ops for anything

**Comment by dpetrisko** [comment]
We have all of this support, so closing (although interesting discussion)
