### ISSUE TITLE
Consider PPArrot branches for either deletion, integration or cryo

### ISSUE THREAD

**Issue by dpetrisko** [black-parrot/black-parrot#170]
Should delete:

- pparrot_fe_lbsbp - static backwards taken branch prediction (unlikely to do)
- pparrot_harden_regfile - hardens integer regfile (already done)
- pparrot_tfan16_backendopt_harden_regfile - hardens integer regfile (already done)
- pparrot_dpam_serdes - Serializing network links (already done through wormhole routing)
- pparrot_dpam_network_redundance - Followup to previous, removes destination id of serdes
- pparrot_richa_amlan_be_rtlchanges - rtl refactoring changes (They overall reduce clarity, I veto inclusion)

These are what jumped out to me, but I haven't looked closely at the rest.  Anyway, they're ~600 commits behind master at this point so they're starting to smell

**Comment by taylor-bsg** [comment]
Seems reasonable.
