### ISSUE TITLE
Trap on misaligned uncached loads / stores

### ISSUE THREAD

**Issue by dpetrisko** [black-parrot/black-parrot#183]
We don't necessarily need to support misaligned loads/stores, but the proposed flow is:

LCE requests an aligned 64 bytes with a byte mask.
CCE responds with the 64 bytes where only the byte mask is guaranteed to be valid.
LCE is responsible for re-aligning the data and muxing out the valid bytes.

**Comment by taylor-bsg** [comment]
Unless otherwise contraindicated by the ISA, I suggest we treat these as an
error for uncached accesses.

M

**Comment by dpetrisko** [comment]
Yep, definitely allowed (through PMAs).

**Comment by dpetrisko** [comment]
- [ ] Add misaligned uncached load/store check after the TLB translation
- [ ] Connect this check to the exception pipeline

**Comment by dpetrisko** [comment]
Closing; long supported
