### ISSUE TITLE
incorrect comment?

### ISSUE THREAD

**Issue by taylor-bsg** [black-parrot/black-parrot#210]
https://github.com/black-parrot/pre-alpha-release/blob/8697ca6c835a66dc042fd3d9b9b7f67bfe88cf32/bp_me/src/v/wormhole/bp_me_cce_to_wormhole_link_master.v#L41

Seems like it is valid and ready, since it goes into a FIFO?

https://github.com/black-parrot/pre-alpha-release/blob/8697ca6c835a66dc042fd3d9b9b7f67bfe88cf32/bp_me/src/v/cce/bp_cce_top.v#L171

**Comment by muwyse** [comment]
Yeah, should be r&v since it feeds direct to a FIFO in bp_cce_top.

Same applies to the async version of the module, which looks to be the one we actually use.

**Comment by muwyse** [comment]
This was fixed at some point as interfaces were refined.
