### ISSUE TITLE
Publish wave.cfgs for End and Top Level

### ISSUE THREAD

**Issue by dpetrisko** [black-parrot/black-parrot#222]
For internal and external use, it would be nice to have sample prettified waveforms so that we can guide users to debug effectively.  These could hook in to our tracers and group by related signals

**Comment by taylor-bsg** [comment]
Or use Neil Ryan’s debugger!

**Comment by dpetrisko** [comment]
*and!

**Comment by dpetrisko** [comment]
Closing; not useful
