### ISSUE TITLE
Identify and justify network buffers

### ISSUE THREAD

**Issue by dpetrisko** [black-parrot/black-parrot#224]
We should enumerate all buffers that go on/off LCE-CCE/CCE-MEM.  Some of these can be one-fifos instead of two, some might be able to be combined.  Some of them are used just for rv conversion.

This can also be done as part of a parallel effort to collapse the coherence networks to 3: req/cmd/resp

**Comment by taylor-bsg** [comment]
Yep!

**Comment by dpetrisko** [comment]
We've mostly eliminated those that can be easily eliminated.  Others will be removed as part of our deserialization efforts, which are tracked elsewhere
