### ISSUE TITLE
Integrate black-parrot into LiteX and LiteX-BuildEnv

### ISSUE THREAD

**Issue by mithro** [black-parrot/black-parrot#228]
[LiteX](https://github.com/enjoy-digital/litex) is an FPGA SoC generator that supports a wide range of FPGA boards and platforms. It currently support multiple soft-cpus, including multiple RISC-V implementations. You can find the details about supported CPUs on this wiki page -> https://github.com/enjoy-digital/litex/wiki/Soft-CPU

It would be awesome to see Black-Parrot in the LiteX system. It would let us very easily compare the resource usage of Black-Parrot to Rocket and VexRISCV.

[LiteX-BuildEnv](https://github.com/timvideos/litex-buildenv) is my environment which uses LiteX to create images for many different FPGA boards. It supports Zephyr, Linux, Micropython and bare metal firmware.

You can find a diagram of this below;
![image](https://user-images.githubusercontent.com/21212/61498497-7f251700-a991-11e9-90a1-bb1e6595a28e.png)

There is also a [Linux on LiteX VexRISCV](https://github.com/enjoy-digital/linux-on-litex-vexriscv) repository which would be cool to port to use Black-Parrot as an alternative option.

You can find the existing CPUs at https://github.com/enjoy-digital/litex/tree/master/litex/soc/cores/cpu
Rocket is probably the closest configuration which can be found at https://github.com/enjoy-digital/litex/blob/master/litex/soc/cores/cpu/rocket/core.py

**Comment by taylor-bsg** [comment]
Nice we will take a look!

**Comment by mithro** [comment]
@taylor-bsg If you need any help figuring out how to do this, feel free to reach out.

**Comment by mithro** [comment]
FYI - This work in in progress at https://github.com/enjoy-digital/litex/pull/278

**Comment by taylor-bsg** [comment]
Completed.
