### ISSUE TITLE
Prerequisites for Ubuntu (byacc)

### ISSUE THREAD

**Issue by scanakci** [black-parrot/black-parrot#269]
byacc is a prerequisite for Ubuntu system. It would be good to update the getting started.

**Comment by dpetrisko** [comment]
Thanks! We haven’t tried getting started on Ubuntu yet, let us know anything else that comes up!

**Comment by dpetrisko** [comment]
Do you know which dependency byacc is used for?

**Comment by scanakci** [comment]
I did not log the full error but I have this error in my records : "pre-alpha-release/external/Makefile.tools:62: recipe for target 'cmurphi' failed"

Hope it helps

**Comment by dpetrisko** [comment]
@muwyse Are you using CMurphi for an ME regression? Should we be :)?  Otherwise, maybe we can put cmurphi under a different make tools target.

**Comment by muwyse** [comment]
It is not used in regressions; it is used for coherence protocol verification, and the protocol should be fixed at this point.

**Comment by dpetrisko** [comment]
Added prereq to latest dev
