### ISSUE TITLE
Include the RISC-V variant in the README?

### ISSUE THREAD

**Issue by mithro** [black-parrot/black-parrot#271]
It would be good to include which RISC-V variant BlackParrot supports in the README. I assume it is something like `rv64im`?

**Comment by dpetrisko** [comment]
Thanks for the feedback! 

BlackParrot is currently RV64IA + MSU privilege modes + SV39 VM.  Longer term, it will support RV64GC. Will update the README to be more clear.

**Comment by dpetrisko** [comment]
Closing with #685
