### ISSUE TITLE
Uncached-only mode is broken

### ISSUE THREAD

**Issue by dpetrisko** [black-parrot/black-parrot#284]
The BE lce_cmd instance only has uncached store logic in its uncached state.  The FE will not go out of reset until it reaches LCE mode normal.  Both of these should be able to forward uncached loads/stores while in uncached mode.

**Comment by muwyse** [comment]
AFAIK, this has been resolved. Both FE and BE LCE's enter and uncached state after clearing internal cache tag/coherence state. The FE/icache only supports uncached load, BE/dcache support uncached load and store.

Closing. New issue can be filed if errors are detected with uncached mode startup or operation.
