### ISSUE TITLE
Critical Path: ME decode + branch

### ISSUE THREAD

**Issue by dpetrisko** [black-parrot/black-parrot#293]
The path is cce_Instr_ram->cce_instr_ram.  More specifically, cce_instr_ram_data->decode->(branch)->alu->(next pc)->cce_instr_ram_addr.

Possible solutions:
1) take another cycle for branches.  This complicates the control flow slightly.
2) Add a decode pipeline stage.  This would solve future critical paths for other instructions.  We could also consider making the CCE regfile synchronous
3) Minor help, make gprs < 64 bits.  Orthogonal to other solutions

**Comment by taylor-bsg** [comment]
Also something we can apply the standard BSG front end tricks to.

M

**Comment by muwyse** [comment]
This should be addressed by commit 3a0a0f8fbc5e9e3a5edd00bd3d020d17538bf3df to dev.
