### ISSUE TITLE
bp_be_detector does not detect 

### ISSUE THREAD

**Issue by taylor-bsg** [black-parrot/black-parrot#335]
https://github.com/black-parrot/black-parrot/blob/7478eaba03c1defcb0c690abbddc809c3a71dcfb/bp_be/src/v/bp_be_checker/bp_be_detector.v#L25

Why

How it should be fixed

**Comment by taylor-bsg** [comment]
I think it should be okay? Maybe provide some more detail?

**Comment by dpetrisko** [comment]
I'm confused.  This is the hazard detector?

**Comment by taylor-bsg** [comment]
;-) demonstrating how to file an issue for the class. They thought it was a
riot.

**Comment by dpetrisko** [comment]
lol :)
