### ISSUE TITLE
Don't recompute page_offset_width_p

### ISSUE THREAD

**Issue by taylor-bsg** [black-parrot/black-parrot#394]
https://github.com/black-parrot/black-parrot/blob/9b3cea5c453d307f893044be6cd5c09f907cab9e/bp_be/src/v/bp_be_mem/bp_be_mem_top.v#L30

Should use bp_page_offset_width_gp instead of computing this.

**Comment by taylor-bsg** [comment]
This and the other bug are the probably the only two places that are holding back VM from working as you change the cache block size.

**Comment by dpetrisko** [comment]
fixed by #658
