### ISSUE TITLE
Enable Verilator tests in CI

### ISSUE THREAD

**Issue by dpetrisko** [black-parrot/black-parrot#415]
Verilator tests pass locally, but fail in CI. Would like to track this down someday, but the logs/reporting of our CI jobs make it very difficult.

- Enable better logging / reporting of runs
- Figure out why tests are failing
- Re-enable tests

**Comment by muwyse** [comment]
I believe this should be resolved now from: https://github.com/black-parrot/black-parrot/pull/457 and https://github.com/black-parrot/black-parrot/pull/461.

As of https://github.com/black-parrot/black-parrot/commit/cd949112f849edc1a102fdde71375d156fa55798, CI is running with top-riscv-verilator job enabled, and passing: https://gitlab.com/black-parrot/black-parrot/pipelines/141232847

Next step is to try re-enabling verilator jobs for multicore, beebs, and coremark.

**Comment by dpetrisko** [comment]
Oh yeah, those all pass.  I ran them manually on the last job, so we can reenable whenever

**Comment by muwyse** [comment]
See: https://github.com/black-parrot/black-parrot/pull/465

**Comment by dpetrisko** [comment]
fixed by #465
