### ISSUE TITLE
Fixed-width CCE message sizes

### ISSUE THREAD

**Issue by sripathi-muralitharan** [black-parrot/black-parrot#427]
The CCE (maybe in other parts of the code as well, but noticed it here) seems to have a few spots where the block widths and the corresponding message sizes are hardcoded to 512 bits. Ideally we would want this to be based on `cce_block_width_p` which makes it easier to support variable cache block sizes. @muwyse could you please have a look at this?

**Comment by dpetrisko** [comment]
https://github.com/black-parrot/black-parrot/blob/dev/bp_me/src/v/cce/bp_cce_msg.v#L725

Here is one of the lines in question

**Comment by muwyse** [comment]
Closed by merge #453
