### ISSUE TITLE
Still true? icache is by default 4-way assoc?

### ISSUE THREAD

**Issue by taylor-bsg** [black-parrot/black-parrot#450]
https://github.com/black-parrot/black-parrot/blob/46ffe11fa106cbcae7820c4ca18552abb79c8f9e/bp_fe/src/v/bp_fe_icache.v#L9

**Comment by dpetrisko** [comment]
Nope, not true. Should just say 2-8 way parametrizable

**Comment by dpetrisko** [comment]
Comment fixed in latest dev
