### ISSUE TITLE
Vivado synthesis issue with dcache 

### ISSUE THREAD

**Issue by dpetrisko** [black-parrot/black-parrot#460]
ERROR: [Synth 8-1587] an enum variable may only be assigned to same enum typed variable or one of its values [/home/petrisko/scratch/bsg_fpga/vu37p/black-parrot/bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v:989

@muwyse, I think you have the last changes here

**Comment by muwyse** [comment]
Looks like it just needs a cast to bp_coh_states_e

**Comment by dpetrisko** [comment]
Oh, I think you’re right.  I thought it was the replication operator. Usually VCS flags assigning bits to an enum, not sure why it made it to vivado

**Comment by muwyse** [comment]
I'm not sure either. Neither the VCS or Verilator linter seems to catch it either

**Comment by muwyse** [comment]
Fixed with: https://github.com/black-parrot/black-parrot/pull/462
Closing.
