### ISSUE TITLE
Certain CSR writes should flush and sync FE

### ISSUE THREAD

**Issue by farzamgl** [black-parrot/black-parrot#503]
Writing some CSRs like satp and some fields of mstatus that control address translations should flush the FE and sync the shadow translations info. This guarantees that the next instruction after the CSR write can see all the side-effects of that update.

**Comment by dpetrisko** [comment]
Which fields of mstatus?

**Comment by farzamgl** [comment]
> Which fields of mstatus?

MPRV, for example, can enable translation in M-mode.

**Comment by dpetrisko** [comment]
MPRV only affects data, not instructions

**Comment by farzamgl** [comment]
You're right. Is the same true for the SUM bit?

**Comment by dpetrisko** [comment]
Yep

**Comment by dpetrisko** [comment]
![image](https://user-images.githubusercontent.com/2322266/82474418-099a4380-9a99-11ea-9659-baaac7b8e420.png)

**Comment by farzamgl** [comment]
That's all then. I think satp should be enough.

**Comment by dpetrisko** [comment]
fixed by #524
