### ISSUE TITLE
Documentation: Possible Typo in LCE-CCE Interface Section

### ISSUE THREAD

**Issue by billythedummy** [black-parrot/black-parrot#528]
In `docs/specification/interface_specification.md`, the section listing the fields of LCE Command Messages writes the following:

>An LCE Command has the following fields:
>...
>- Source ID - sending LCE ID

Based on the specification for the LCE Response network and looking at the code in `bp_fe/src/v/bp_fe_lce_cmd.v`, is the Source ID supposed to be the sending CCE ID instead?

**Comment by dpetrisko** [comment]
Yep, typo.  Feel free to PR to dev
