### ISSUE TITLE
Investigate impact of supporting L2 atomics in BedRock

### ISSUE THREAD

**Issue by dpetrisko** [black-parrot/black-parrot#557]
L2 atomics are useful for highly contended aggregation, such as parallel reduction. We should support this option in BedRock, so that LCEs can request the CCE to perform an atomic operation

Changes required:
[X] Add atomic message types to LCE/CCE IF
[X] Add atomic message types of CCE/MEM IF
[X] Add parameterized atomic operation to L1
[  ] Integrate bsg_cache atomics from this PR [](https://github.com/bespoke-silicon-group/basejump_stl/pull/298)

Other possible features:
[ ] Atomic support with CCE ucode
[ ] Add flag for "no return" atomics (rd == x0) which are non-blocking

**Comment by muwyse** [comment]
See this branch for initial support in the FSM CCE: https://github.com/black-parrot/black-parrot/tree/l2_atomics_cce, which builds on branch https://github.com/black-parrot/black-parrot/tree/feature_enable_l2atomics

**Comment by dpetrisko** [comment]
Partially fixed with #765

**Comment by dpetrisko** [comment]
All are implemented except for L2 LR/SC, so closing for now
