### ISSUE TITLE
"make tools" results in riscv-gnu-toolchain "critical programs are missing or too old"

### ISSUE THREAD

**Issue by tanglingshu** [black-parrot/black-parrot#564]
**Issue**: while running "make tools" on kk9, I received the following error message:
*** These critical programs are missing or too old: make
*** Check the INSTALL file for required versions
[stamps/build-glibc-linux-rv64ima-lp64] Error 1
[gnu_build] Error 2

**Platform**: CentOS 7

**Suggested solution**: scl enable devtoolset-8 bash

This serves as a reminder to add the suggested solution to the docs

**Comment by dpetrisko** [comment]
Closing with #685
