### ISSUE TITLE
Cosim mismatch: fpu returns a 0 while a -0 is expected

### ISSUE THREAD

**Issue by Songchun-Li** [black-parrot/black-parrot#611]
A cosim mismatch occurs at the me_dev branch, in the test of whetstone, beebs. And the corresponding instruction is fmul.d fa2, fa4, fa2. The fpu returns a 0 while a -0 should be returned.
<img width="910" alt="Screen Shot 2020-08-21 at 8 46 53 PM" src="https://user-images.githubusercontent.com/26761214/90948028-84a02c80-e3ef-11ea-840c-cd4184c3d3fe.png">

**Comment by dpetrisko** [comment]
Also occurs in stb-perlin and minver

**Comment by dpetrisko** [comment]
Fixed with #1001
