### ISSUE TITLE
Rebase Dromajo onto latest

### ISSUE THREAD

**Issue by dpetrisko** [black-parrot/black-parrot#686]
Lots of cool new features and better documentation, including a better custom bootrom flow

https://github.com/chipsalliance/dromajo/commits/master

**Comment by farzamgl** [comment]
Dromajo bumped on sw_dev: https://github.com/black-parrot/black-parrot/commit/70b62d1c616f41b945489381797c949150e2c74e

**Comment by dpetrisko** [comment]
Cool!
