### ISSUE TITLE
Test failure with Unicore No L2 cfg

### ISSUE THREAD

**Issue by Songchun-Li** [black-parrot/black-parrot#700]
### me_dev fails 4 riscv tests with e_bp_unicore_no_l2_cfg
![image](https://user-images.githubusercontent.com/26761214/101323251-39365080-381d-11eb-89ab-de2fa70064b0.png)
It seems these failures is from the same root cause. And the error messages says that the both port 0 and port 1 attempt to read and write the same address of the int_regfile at  the backend scheduler.
![image](https://user-images.githubusercontent.com/26761214/101323352-64b93b00-381d-11eb-9c44-05d117a95607.png)

**Comment by dpetrisko** [comment]
Opened #723 , closing this
