### ISSUE TITLE
xxd dependency

### ISSUE THREAD

**Issue by getziadz** [black-parrot/black-parrot#701]
I encountered a dependency on `xxd` (vim-common package) which was not specified anywhere.
Though trivial to resolve, it may be beneficial to create a section where you list dependecies for getting started with BlackParrot.
The section could include a description of systems that the BlackParrot infrastructure has been tested.

System: Fedora 33

**Comment by dpetrisko** [comment]
You can find this info here in the getting started guide:

https://github.com/black-parrot/black-parrot/blob/master/docs/getting_started.md#prerequisites

Would happily accept a PR for additional Fedora requirements!

**Comment by getziadz** [comment]
The CentOS entry should cover Fedora and RHEL distributions. I don't see vim-common on the prerequisites list but it may be pulled from one of the other packages or it could be that the standard distribution comes with it preinstalled.

**Comment by dpetrisko** [comment]
Yeah, I'm not sure.  The CentOS entry is the same as the Dockerfile I use so it should be a clean install, but I always include vim before adding the dependencies. Adding vim-common to the list is reasonable a safety net
