### ISSUE TITLE
BedRock macros widths and declarations are strongly coupled

### ISSUE THREAD

**Issue by dpetrisko** [black-parrot/black-parrot#725]
If you try to use  

```
`declare_bp_bedrock_mem_if(paddr_width_p, uce_mem_data_width_lp, lce_id_width_p, lce_assoc_p, uce);
```
without 
```
`declare_bp_bedrock_mem_if_widths(paddr_width_p, uce_mem_data_width_lp, lce_id_width_p, lce_assoc_p, uce)
```
it will complain of a missing payload width declaration.  To fix, can either:

1) pass in the payload_width_lp as a parameter
2) recalculate payload width internally in declare_bp_bedrock_mem_if, using ____payload_width_lp = to obfuscate the name.

**Comment by muwyse** [comment]
@dpetrisko can you take a look at this commit: https://github.com/black-parrot/black-parrot/commit/c48fe7dfeac7647c3ac217498f5ef2c6e2364c2a

I think it fixes the problem (the ME testbench compiled and ran without issue using vcs)

**Comment by dpetrisko** [comment]
Perfect!
