### ISSUE TITLE
Convert LCEs to use ready_and instead of ready_then

### ISSUE THREAD

**Issue by muwyse** [black-parrot/black-parrot#846]
Since the LCEs connect to networks in BP they should really use ready_and interfaces for the request, command, and response networks.

**Comment by dpetrisko** [comment]
Yep, I have a branch somewhere I started to work on that. Shouldn’t be too bad to implement (and no cost, since the handshakes are in an FSM anyway)

**Comment by dpetrisko** [comment]
Buggy first try here: https://github.com/black-parrot/black-parrot/tree/top_dev_fix_lcehelpful

**Comment by muwyse** [comment]
This will be fixed when LCE is updated to use BedRock Burst
