### ISSUE TITLE
Swap out hardened RAM generics in bsg_sv2v flow

### ISSUE THREAD

**Issue by dpetrisko** [black-parrot/black-parrot#896]
## Branch / Commit Hash
any

## Area
bsg_sv2v

## Current behavior
bsg_sv2v currently pickles the entire BlackParrot core without replacing the RAMs. This takes a decent amount of time ~20-30m. 

## Desired behavior
We should swap the RAMs with hardened generics. Additionally, this is a good excuse to have a formal list of the RAMs intended to be hardened.

## Proposed solution
- [x] Add a list of hardened RAMs (in JSON format?)
- [x] Add hardened generic wrappers / wrapper macros (may also live in basejump
- [x] Modify bsg_sv2v flow to do hardened swap

## Analysis
Reduced runtime in bsg_sv2v.

## Verification
Manual inspection and runtime analysis

## Additional context
 [Example of hard wrapper](https://github.com/bespoke-silicon-group/bsg_pipeclean_suite/blob/master/black_parrot_fe_only_2019_03_11/harden_me.v))

**Comment by taylor-bsg** [comment]
@stdavids i thought we had some kind of method for these hard rams? Was it part of IDF or something?

**Comment by dpetrisko** [comment]
The methodology is to use this swap:

https://github.com/bespoke-silicon-group/basejump_stl/blob/master/hard/pickle_40/bsg_mem/bsg_mem_1rw_sync.v

and then include this hardened file for sims.

https://github.com/bespoke-silicon-group/bsg_pipeclean_suite/blob/master/black_parrot_fe_only_2019_03_11/harden_me.v

For the actual sv2v here, we just have to swap out the memory and the wrapper will be blackboxed. If we want to sim the sv2v, then we need the wrapper functional modules to simulate with.
