### ISSUE TITLE
Header is repeated here N times, we don't want to store it each time or it'll be a huge waste. We should have a data buffer and a smaller header buffer

### ISSUE THREAD

**Issue by dpetrisko** [black-parrot/black-parrot#913]
Header is repeated here N times, we don't want to store it each time or it'll be a huge waste. We should have a data buffer and a smaller header buffer

_Originally posted by @dpetrisko in https://github.com/black-parrot/black-parrot/pull/893#discussion_r681551861_

**Comment by muwyse** [comment]
This has been fixed on me_dev with #893
