### ISSUE TITLE
BP sets FS field  to DIRTY during exception when FS is OFF.

### ISSUE THREAD

**Issue by scanakci** [black-parrot/black-parrot#969]
## Branch / Commit Hash
What version of BlackParrot are you running?
Commit: 5d6620f4bf5f6a31b3ecbb3dfdf92ef485a9aa6c

## Area
BP RTL

## Current behavior
When FS is OFF (i.e., 00), updating fcsr raises an exception by BP as expected. However, BP updates FS field in mstatus. Specifically, BP sets it to DIRTY instead of keeping it as OFF. Dromajo does not change FS field value during the exception. 
execute an instruction that attemps to write to fcsr (e.g., csrrs   a1,fcsr,a3) when FS is OFF. 

## Expected behavior
FS in mstatus should stay OFF if an exception happens when FS is disabled.

## Proposed solution
N/A

## Analysis
N/A

## Verification
in bp_top/sync folder, run the following command. I attached the prog.riscv
make -B build.sc sim.sc COSIM_P=1 CMT_TRACE_P=1 SUITE=bp-tests PROG=prog

## Additional Context
I attached the necessary logs/binary/dumps.
[fcsr_mismatch.tar.gz](https://github.com/black-parrot/black-parrot/files/7600044/fcsr_mismatch.tar.gz)

Dromajo Output:
Running with Dromajo cosimulation
[error] HARTID: 0
[error] EMU PC 000000008000014c, DUT PC 000000008000014c
[error] EMU INSN 00000097, DUT INSN 00000097
[error] EMU WDATA 000000008000014c, DUT WDATA 000000008000014c
[error] EMU MSTATUS a00001800, DUT MSTATUS 8000000a00007800
[error] DUT pending exception -1 pending interrupt -1
NBF loader done!
COSIM_FAIL: instruction mismatch

**Comment by dpetrisko** [comment]
Fixed with #968
