### ISSUE TITLE
BP wrongly sets sepc[0] 

### ISSUE THREAD

**Issue by scanakci** [black-parrot/black-parrot#970]
## Branch / Commit Hash
What version of BlackParrot are you running?
5d6620f4bf5f6a31b3ecbb3dfdf92ef485a9aa6c

## Area
BP RTL

## Current behavior, Expected behavior
According to SPEC, sepc[0] must be always zero. When a random program writes to sepc (e.g.,  csrrsi  a2, sepc, 31), BP updates sepc[0]. When reading sepc with 'csrr sp,sepc', I can see that spec[0] is 1. Dromajo aligns with SPEC (i.e., sepc[0] is 0).

## Proposed solution
N/A

## Analysis
N/A

## Verification
in bp_top/sync folder, run the following command. I attached the prog.riscv
make -B build.sc sim.sc COSIM_P=1 CMT_TRACE_P=1 SUITE=bp-tests PROG=prog

## Additional Context
I attached the necessary logs/binary/dumps.
[sepc_mismatch.tar.gz](https://github.com/black-parrot/black-parrot/files/7611143/sepc_mismatch.tar.gz)

Running with Dromajo cosimulation
csr_read: invalid CSR=0x3b4
[error] HARTID: 0
[error] EMU PC 0000000080000188, DUT PC 0000000080000188
[error] EMU INSN 14102173, DUT INSN 14102173
[error] EMU WDATA 000000000000001c, DUT WDATA 000000000000001f
[error] EMU MSTATUS 8000000a00007800, DUT MSTATUS 8000000a00007800
[error] DUT pending exception -1 pending interrupt -1
NBF loader done!
COSIM_FAIL: instruction mismatch

**Comment by dpetrisko** [comment]
Fixed with #968
