### ISSUE TITLE
Some FPU operations not producing NaNs as they should

### ISSUE THREAD

**Issue by mysoreanoop** [black-parrot/black-parrot#971]
## Branch / Commit Hash
a4779726d0cc5d3427d2d26cb5ae8665c9361375
## Area
FPU submodules
## Current behavior
Some operations (part of a contrived test assembly code) which would evaluate to NaN in Spike/Dromajo/Rocket are not being evaluated to NaN in BP.
(BP doesn't seem to infer NaNs from SP values read off of DP registers. As a result, any operation which should have otherwise seen NaN as one of the operands will operate normally producing a non-NaN value.)

## Expected behavior
Conformance with Spike/Dromajo.
(When running SP operations from SP values inferred off of DP registers, if the SP values are not explicitly boxed apriori, the operation has to infer the SP operand values as NaNs (barring the coincidental boxed value maybe?). Here's some relevant discussion: https://groups.google.com/a/groups.riscv.org/g/isa-dev/c/y8CkRopfEWk)

## Proposed solution
Check if operands are boxed or not, and if not, consider them to be NaNs (if not already doing so)

## Verification
Running the same test case against Dromajo/Spike should match the commit traces.

## Additional Context
The table below reads the rd for Black Parrot, 
Dromajo, Spike, Rocket, and rs1, rs2, rs3 for 2 operations (fnmadd, and fdiv -- there are more similar mismatches for most FPU operations). Subsequent lines read the decoded value of the line above it
![image](https://user-images.githubusercontent.com/29160122/143730597-2688a384-9407-4a7f-93a7-3b8fe89bd979.png)
[fail.tar.gz](https://github.com/black-parrot/black-parrot/files/7612856/fail.tar.gz)

**Comment by dpetrisko** [comment]
I believe this issue should be resolved with latest dev

**Comment by black-parrot** [comment]
Do we have tests for these cases checked in?

**Comment by dpetrisko** [comment]
Yes, tests commited with #1007
