### ISSUE TITLE
BP ignores misaligned memory access exception in S-mode

### ISSUE THREAD

**Issue by Yuan-Mao** [black-parrot/black-parrot#995]
## Branch / Commit Hash

Current master branch(dd2d8453a49b0f069e96f175afe97968dac205e1)

## Area
Misaligned Memory Access

## Current & Expected behavior
Hi,
When I was trying to bring up Linux kernel 5.15 on BP, I found a mismatch between Dromajo and BP during co-simulation. It happens when BP does its first misaligned memory access in S-mode. Dromajo will jump to M-mode and handle the memory access exception properly, but BP seems to just ignore it and continue its execution.

[This code from Linux 5.15](https://elixir.bootlin.com/linux/v5.15/source/arch/riscv/lib/memmove.S#L6) is the code that reveals this issue. Back in kernel 5.7, there's no such assembly code so every memory copy is memory aligned, but in kernel 5.15 we can easily have plenty of unaligned memory access with this piece of code (it uses lw, sw even if src and dst are not 4-byte aligned).

To reproduce this issue, I have written a program that does misaligned memory access. Please find the attached files 'opensbi.elf' and 'opensbi.nbf' here: [test.zip](https://github.com/black-parrot/black-parrot/files/7782667/test.zip).
'opensbi.elf' is basically an opensbi image with a simple payload(prog.c) that uses the memmove function(memmove.S) from [Linux 5.15](https://elixir.bootlin.com/linux/v5.15/source/arch/riscv/lib/memmove.S#L6) to do some misaligned memory access.

![Screenshot from 2021-12-27 20-28-57](https://user-images.githubusercontent.com/32671969/147528185-79604a55-39e8-4068-8fce-f80902c8dce7.png)

**Comment by dpetrisko** [comment]
Hi, that makes sense we don't currently detect misaligned exceptions in any priv mode as these are exceptionally rare code. Interesting that Linux now does this. Please make a PR to [bp-tests](https://github.com/black-parrot-sdk/bp-tests) with the failing minimal test case

**Comment by dpetrisko** [comment]
Hi, I have added support here: 
https://github.com/black-parrot/black-parrot/pull/997
https://github.com/black-parrot-sdk/bp-tests/pull/26

**Comment by dpetrisko** [comment]
Fixed
